name: Auto Terraform Apply
on:
  push:
    branches:
      - "master"
    paths:
      - "terraform/**"
jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TF_TOKEN }}
          export_default_credentials: true

      - name: set terrraform env
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4
          cli_config_credentials_token: ${{ secrets.GCP_TF_TOKEN }}

      - name: init
        id: init
        run:  |
          export TF_VAR_project_id=${{ secrets.GCP_PROJECT_ID }}
          terraform init
        continue-on-error: false

      - name: apply
        id: apply
        run:  |
          export TF_VAR_project_id=${{ secrets.GCP_PROJECT_ID }}
          terraform apply -auto-approve
